version: "3.9"
services:
 apieindproject:
  image: r0793084/eindproject-jesse-dierckx-api
  ports:
    - "8000:8000"
  volumes:
    - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume: